# Matemática básica con una matriz de 1D en Numpy

In [11]:
a = [1, 2, 3,]
print(a)
print(a+a)

[1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [6]:
b = a
type(b)

list

In [7]:
import numpy as np

In [10]:
b = np.array(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3]


In [13]:
print(b+b)
print(b + 1)
print(b**2)
print(np.sin(b))

[2 4 6]
[2 3 4]
[1 4 9]
[0.84147098 0.90929743 0.14112001]


In [32]:
A = 5
print("Imprimir los " + str(A) + " primeros números usando la función 'range'")
for i in range(A):
    print( i, end=', ')

Imprimir los 5 primeros números usando la función 'range'
0, 1, 2, 3, 4, 

# Creación de matrices con un rango y una matriz lineal

# Comparación de velocidad con listas