# Matrices
Hemos de usar la librería Numpy

In [1]:
import numpy as np

In [2]:
var01 = np.array([1, 2, 3, 4])

In [3]:
print(var01)

[1 2 3 4]


In [4]:
var01[0]

1

In [5]:
var01[0:4]

array([1, 2, 3, 4])

In [6]:
var01[0], var01[3]

(1, 4)

In [7]:
var02 = np.array([1, -3, 0, 1, -5])

In [8]:
var02[-1]

-5

In [9]:
var02[0:-1]

array([ 1, -3,  0,  1])

In [10]:
var02[4:5]

array([-5])

In [11]:
var02[4]

-5

In [13]:
var02[4:-1]

array([], dtype=int64)

In [12]:
var02[-2:-1]

array([1])

## Array de una dimensión

In [14]:
var03 = np.linspace(-10, 10, 5)
var03

array([-10.,  -5.,   0.,   5.,  10.])

In [15]:
print(var03)

[-10.  -5.   0.   5.  10.]


## Creamos una copia de var02

1° Con la sintaxis foo02 = foo01 lo que se está creando es una declaración que referencia los valores de foo01 a foo01, se está haciendo un puntero.

In [16]:
var04 = var03

In [17]:
var04

array([-10.,  -5.,   0.,   5.,  10.])

In [18]:
var04[0]

-10.0

In [19]:
var04[0] = 0

In [20]:
var04

array([ 0., -5.,  0.,  5., 10.])

In [21]:
var03

array([ 0., -5.,  0.,  5., 10.])

2° Para copiar todos los elementos de una matriz lo mejor será hacer foo02[:] = foo01[:]

In [22]:
var03[0]

0.0

In [23]:
var03[0] = 30

In [24]:
var03

array([30., -5.,  0.,  5., 10.])

In [25]:
var04

array([30., -5.,  0.,  5., 10.])

Observamos que si cambiamos el valor del primer elemento a var03 en consecuencia simulteanea ocurré lo mismo para var04, por ello se identifica la referenciación que existe entre ambos.

In [26]:
print(var03)

[30. -5.  0.  5. 10.]


In [27]:
type(var03)

numpy.ndarray

Creamos una copia de var03 como var05

var05[:] = var03[:]
Este es el esquema correcto para crear una copia con todos sus elementos para una matriz, aunque antes deberíamos de contar con una matriz de las mismas dimensiones vacía.

Notamos que nos imprime error, ello ocurre porque hacer una copia de esta manera exige que primero se genere una matriz vacía con la misma cantidad de elmeentos de var03, para ello hacemos:

In [28]:
#print(var05)

In [37]:
print(np.empty_like(var03))

[30. -5.  0.  5. 10.]


In [38]:
var05 = np.empty_like(var03)
print(var05)

[30. -5.  0.  5. 10.]


In [39]:
len(var05)

5

## Entendiendo np.empty_like(varX)

Debemos contar con la variable 'a' , esta guarda en memoria a una matriz de dimensiones nxm , lo que se desea es crear una matriz equivalente en las dimensiones, por lo tanto hacemos:

In [41]:
a = ([1, 2, 3], [4, 5, 6])
print(a)

([1, 2, 3], [4, 5, 6])


In [42]:
np.empty_like(a)

array([[140480226511032, 140480227276704, 140480175869864],
       [140480227517040, 140480227405528, 140480175844928]])

La nueva matriz generada a partir de 'a' tiene la misma cantidad de elementos y en las mismas posiciones, aunque los elementos son random

In [43]:
np.empty_like(var03)

array([30., -5.,  0.,  5., 10.])

In [44]:
var003 = [30, 5, 0, 5, 10]

In [45]:
np.empty_like(var003)

array([     94561522858528,      94561518026320,  288522854901811714,
        720868427853597186, 1010499607555279363])

Acabamos de descubrir que la función 'np.empty_like(var)' crea una nueva matriz equivalente siempre y cuando sus terminos hayan sido guardados de la forma de números enternos, en el caso sean decimales la nueva matriz será identica a la anterior.

In [46]:
a = np.array([[1., 2., 3.],[4., 5., 6.]])

In [47]:
np.empty_like(a)

array([[6.94064523e-310, 4.67195998e-310, 6.94064544e-310],
       [6.94064124e-310, 6.94063731e-310, 6.94064342e-310]])

In [48]:
type(a)

numpy.ndarray

In [49]:
np.empty_like(var03)

array([1.5e-322, 2.5e-323, 0.0e+000, 2.5e-323, 4.9e-323])

In [50]:
var05 = np.empty_like(var03)

In [51]:
print(var05)

[1.5e-322 2.5e-323 0.0e+000 2.5e-323 4.9e-323]


Para mejor entendimiento de np.empty_like(a) revisar el siguiente enlace: [Documentación desde Scipy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html)

In [52]:
var05[:] = var03[:]

In [54]:
print(var05)

[30. -5.  0.  5. 10.]


In [55]:
type(var05)

numpy.ndarray