# 1º Curso de Introducción a la Fluidodinámica con el Lenguaje de Programación Python (Clase N02)

### Operaciones con arrays desde la librería Numpy

La librería Numpy nos acompañará para el desarrollo de calculos donde se requiera mayor potencia con la finalidad de aumentar la velocidad de procesamiento, a continuación veamos la ecuación:

$$u^{n+1}_i = u^n_i-u^n_{i-1}$$

Si tenemos el vector definido para $u^n = [0, 1, 2, 3, 4, 5]\ \ $, encontramos los valores de $u^{n+1}$ haciendo interaciones sobre los valores de $u^n$ con el esquema `for`.

In [1]:
import numpy as np

u = np.array((0, 1, 2, 3, 4, 5))

for i in range(1, len(u)): # i : contador que recorre el intervalo generado desde 1 hasta el valor de len(u)
    print(u[i]-u[i-1])

1
1
1
1
1


In [2]:
# Otro calculo:
print("Ejemplo de operaciones con listas:")
print("Nuestro vector u es:" + str(u))
print("------")
print("Ahora hacemos:")
print("u[1:] = " + str(u[1:]))
print("u[0:-1] = " + str(u[0:-1]))
print("-------")
print("u[1:]-u[0:-1] = " + str(u[1:]-u[0:-1]))


Ejemplo de operaciones con listas:
Nuestro vector u es:[0 1 2 3 4 5]
------
Ahora hacemos:
u[1:] = [1 2 3 4 5]
u[0:-1] = [0 1 2 3 4]
-------
u[1:]-u[0:-1] = [1 1 1 1 1]


### Velocidad en calculo

In [3]:
x = 2.
y = 2.
nx = 81
ny = 81
nt = 100
c = 1
dx = x/(nx-1)
dy = y/(ny-1)
sigma = .2
dt = sigma*dx

y1 = .5
y2 = 1.

x1 = .5
x2 = 1.

ue = 2

x = np.linspace(0, x, nx)
y = np.linspace(0, y, ny)

u = np.ones((ny,nx))
un = np.ones((ny,nx))
print("u:")
print(u)
print("un:")
print(un)

u[int(y1/dy):int(y2/dy+1) , int(x1/dx):int(x2/dx+1)]=ue
print("Nuevo valor de u:")
print(u)

u:
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
un:
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Nuevo valor de u:
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


**Nota:** Usaremos la función mágica ``%%timeit`` para medir el tiempo aproximado de la ejecución de nuestro programa.

In [4]:
%%timeit
u = np.ones((ny,nx))
u[int(y1/dy):int(y2/dy+1),int(x1/dx):int(x2/dx+1)]=ue

for n in range(nt+1):
    un[:] = u[:]
    for i in range(1, len(u)):
        for j in range(1, len(u)):
            u[i,j] = un[i,j]-(c*(dt/dx)*(un[i,j] - un[i-1,j]))-(c*(dt/dy)*(un[i,j]-un[i,j-1]))
            u[0,:] = 1
            u[-1,:] = 1
            u[:,0] = 1
            u[:, -1] = 1
            
            

4.51 s ± 108 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Ahora hacemos un nuevo calculo:

In [5]:
%%timeit
u = np.ones((ny,nx))
u[int(y1/dy):int(y2/dy+1),int(x1/dx):int(x2/dx+1)]=ue

for n in range(nt+1):
    un[:] = u[:]
    u[1:,1:]=un[1:, 1:] - (c*-(dt/dx)*(un[1:, 1:]-un[0:-1, 1:])) - (c*(dt/dy)*(un[1:,1:]-un[1:,0:-1]))
    u[0,:] = 1
    u[-1,:] = 1
    u[:,0] = 1
    u[:, -1] = 1

8.51 ms ± 79.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Los ejercicos que hemos llegado a abordar hasta hora unicamente se estaba logrando para 1-D , ahora lo haremos para 2-D